### ISSUE TITLE
Change Spectrum.bin_edges_keV to a property

### ISSUE THREAD

**Issue by jccurtis** [lbl-anp/becquerel#101]
The bin_edges_keV array should be hidden: `_bin_edges_keV` and the setter should perform this work which is currently in the `__init__`:

```python
        if bin_edges_kev is None:
            self.bin_edges_kev = None
        elif len(bin_edges_kev) != len(self) + 1:
            raise SpectrumError('Bad length of bin edges vector')
        elif np.any(np.diff(bin_edges_kev) <= 0):
            raise ValueError(
                'Bin edge energies must be strictly increasing')
        else:
            self.bin_edges_kev = np.array(bin_edges_kev, dtype=float)
```

**Comment by cosama** [comment]
Slightly related: While writing the plotting stuff, I also saw the need for a channel_edge property. It is in the SpectrumPlotter class for now, but maybe should be moved to the Spectrum itself, seems more natural to me.
