### ISSUE TITLE
Parsers shouldn’t duplicate core tools

### ISSUE THREAD

**Issue by jccurtis** [lbl-anp/becquerel#103]
The spectrum_file in parsers duplicates code from Spectrum and ECal in core. The parsers should be updated to use the core tools as appropriate based on the file ICD (ie quadratic interpolation, etc). We should take care to not create circular imports. 

TODO:

- [ ] Cleanup the inheritance between `SpectrumFile` and the type-specific parsers like `SpeFile`
- [ ] Add verbosity option to `SpectrumFile` loading (for silent mode when loading lots of files)
- [ ] Change `AssertionError` when file is not found to a more useful error _including_ the actual path which cannot be found

**Comment by markbandstra** [comment]
The inheritance between `SpectrumFile` and the type-specific parsers like `SpeFile` is messy and needs to be cleaned up. Whoever works on this issue might consider doing this as well.

**Comment by jccurtis** [comment]
Agreed! I'll have a look.
