### ISSUE TITLE
Spectrum multiplication, addition and subtraction problems

### ISSUE THREAD

**Issue by cosama** [lbl-anp/becquerel#112]
* The spectrum has no `__rmul__` method, thus `2*spectrum` produces an error, while `spectrum*2` works. This should be easy to add, it would be pretty much just a copy of `__mul__.` This doesn't affect division, I think `2/spectrum`, doesn't make sense.

* If both spectra in addition/subtraction don't have cps defined an error is thrown. I think in that case it should just ignore cps. If one has cps defined and the other does not then, maybe it would make sense to throw an error, or maybe better not define the cps in the new spectrum (which then will cause an error once this method will be accessed in the new spectrum).

**Comment by cosama** [comment]
I just add this here, even though it is only slightly related. If an array with negative values is passed to the spectrum class it causes a warning in  `counts, uncs, lambda x: np.maximum(np.sqrt(x), 1))`. Not sure what to do about that.

**Comment by jccurtis** [comment]
- Good catch, I've moved the negative input discussion to #113.
- The spectra sub operation doesn't make sense unless you are operating on time dependent values. Can you think of a use case in which you would subtract counts?
- The spectra add operation should be able to handle counts when no cps / livetime are defined. Is this not the case? We should add a test ...

**Comment by cosama** [comment]
To be honest the reason why this all popped up is because I needed a spectrum with negative counts to test errors related to y-limits when creating log plots (which can not include negative values). The only two ways to get one is to either pass a np array with negative values to the constructor or to subtract a spectrum from the other. It is something that probably is hardly ever encountered in reality.
* The only case I could think of the subtraction being necessary without having lifetimes, would be if you know that two measurements are the same lifetime, but you don't know what it is. However, then it would be okay to just use a random value, but maybe better to allow for that.
* The add operator calls the spec.cps attribute, which throws an error if spec._cps or spec.lifetime is not defined. We could simply catch the error and not assign anything to spec._cps in the new spectrum if that happens.

**Comment by cosama** [comment]
I started to work on this (in particular the right multiplication) and found the following interesting behavior after adding a `__rmul__` method:

`np.array([2,3]) * spectrum` returns a list of two spectra, the first multiplied by two, the second multiplied by 3. The reason for this is that it does use the `__mul__` method of numpy, which does internally call the multiplication method for each element of the numpy array with the spectrum class, which is the  spectrum __rmul__ method in this case).

I was a bit surprised that this happened, but I could see that this might be useful and it seems to be quite logic. It would for example allow to initiate an array of spectrum with `spec_array = np.ones(spec_array_len)*spec`

Is that something we want? If so we probably should implement `spectrum *  np.array([2,3])` too, otherwise we have to think how to block this behavior without begin to intrusive in possible other methods that would like to define a `__mul__` method with a spectrum class.

**Comment by cosama** [comment]
There is actually a test for subtraction without live time causing an error.

**Comment by cosama** [comment]
Spectra addition right now does:

* Add counts and add lifetimes if available
or
* Add cps.

The first one corresponds to a longer measurement, the second one to a measurement with a stronger source. I think it is very confusing to do one or the other.

**Comment by jccurtis** [comment]
- [ ] @cosama will fix multiplication with a small PR
- [ ] @jccurtis will fix add/sub as part of #122
