### ISSUE TITLE
Negative inputs to Spectra

### ISSUE THREAD

**Issue by jccurtis** [lbl-anp/becquerel#113]
@cosama noted the a Spectra input with negative counts causes a warning when calculating uncertainty via `np.sqrt`. See: https://github.com/lbl-anp/becquerel/blob/develop/becquerel/core/spectrum.py#L126-L146

```python
        if counts is not None:
            if len(counts) == 0:
                raise SpectrumError('Empty spectrum counts')
            self._counts = handle_uncs(
                counts, uncs, lambda x: np.maximum(np.sqrt(x), 1))
            if livetime is None:
                self.livetime = None
            else:
                self.livetime = float(livetime)
            self._cps = None
        else:
            self._counts = None
            if livetime is None:
                self.livetime = np.nan  # default for CPS-based spectra
            else:
                self.livetime = livetime
                # TODO should this be allowed?
                #   all calculations with CPS return livetime=np.nan anyway...
            if len(cps) == 0:
                raise SpectrumError('Empty spectrum counts')
            self._cps = handle_uncs(cps, uncs, lambda x: np.nan)
```

This can cause confusion and doesn't gracefully handle the situation. I propose a check for negative values in the `counts` which raises an error. Thoughts?

**Comment by markbandstra** [comment]
I think it would be useful to allow negative `Spectrum` count values in some cases. For example, when background subtraction is performed some parts of the resulting spectrum may be consistent with zero and therefore be randomly scattered above and below zero.

What do you think about the following:
- By default, if `Spectrum` is initialized with only `counts`:
    - Enforce that those values must be non-negative and we assign `uncs` assuming Poisson statistics, as [we currently do](https://github.com/lbl-anp/becquerel/blob/78477b597bfeede871af642f68af6016e0ad1dbc/becquerel/core/spectrum.py#L129-L130). This will avoid taking the`sqrt` of a negative number and will raise an exception that will make clear what the problem is. (This is @jccurtis 's suggestion.)
    - Also set a flag such as `self.poisson = True` to mark the fact that the uncertainties are Poisson.
- If `Spectrum` is initialized with both `counts` and `uncs`:
    - Do not enforce non-negativity. (This could be true for a background-subtracted `Spectrum`.)
    - Set `self.poisson = False`.

I think the `Spectrum.poisson` flag would be useful especially later when we implement fitting to know whether the data in a `Spectrum` represent Poisson counts or non-Poisson counts with uncertainties that are a Gaussian approximation. Would also contribute to #15.

This would require very little changes to the existing code.

**Comment by cosama** [comment]
I came to the same conclusion as Mark did: 
* if `counts` and `uncs` are provided we should let the user do whatever, 
* if only counts are provided, we raise an error when negative values are encountered (maybe with a hint that the behavior can be altered with providing `uncs`).

If we set a flag as Mark suggested, we have to unset the flag on subtraction of two spectra (also relates to #112).
