### ISSUE TITLE
Cleanup tool module imports

### ISSUE THREAD

**Issue by jccurtis** [lbl-anp/becquerel#115]

**Comment by markbandstra** [comment]
Can someone remind me what this issue is specifically calling for?

Here is how we currently access the main classes and functions in the tools:
```python
from becquerel.tools import element  # element.Element
from becquerel.tools import isotope  # isotope.Isotope
from becquerel.tools import isotope_qty  # isotope_qty.IsotopeQuantity, isotope_qty.NeutronIrradiation
from becquerel.tools import materials  # materials.fetch_element_data, materials.fetch_compound_data
from becquerel.tools import nndc  # nndc.fetch_wallet_card, nndc.fetch_decay_radiation
from becquerel.tools import xcom  # xcom.fetch_xcom_data
```

Should we move all of these classes and functions into the `bq.tools` namespace?

**Comment by jccurtis** [comment]
I am using the import structure:

```python
import becquerel as bq

bq.tools.nndc. fetch_decay_radiation
# etc ...
```

Our current structure could get crowded if we bring all the functions/classes to the top level namespace. I like the grouping of these tools into `tools` and the core tools brought up to the main level: `Spectrum`, etc.

**Comment by markbandstra** [comment]
Right, so instead of
```python
import becquerel as bq

bq.tools.nndc.fetch_decay_radiation(...)
```
we want
```python
import becquerel as bq

bq.tools.fetch_decay_radiation(...)
```
That is, remove the third level in the module hierarchy (e.g., `nndc`) so that everything is in `bq.tools`?
