### ISSUE TITLE
EnergyCal should perform fit on initialization or report proper Errors

### ISSUE THREAD

**Issue by cosama** [lbl-anp/becquerel#117]
If one creates an energy calibration object at this point and does not call the update_fit function one gets an obscure KeyError about coeffs when applying the calibration to a spectrum, that does not help at all to understand what is going on (at least I was very confused).

Either we catch the error and tell the users that they need to call the update_fit function for it to work, or we call the update_fit function on initialization (my prefered choice) and make sure the fit coefficients are always defined properly.

**Comment by jccurtis** [comment]
Can you upload some sample code? I agree that this should be in the `from_points` constructor but **not** in the base init because you can make a calibration from coefficients and not the calibration points. What do you think? 

Also, this test could be updated: https://github.com/lbl-anp/becquerel/blob/develop/tests/energycal_test.py#L215-L219

**Comment by cosama** [comment]
The test you found it exactly what I was referring too. I agree it should not be in the init, but the from_points method should call it automatically. That also won't break backwards compatibility (if we even care) as you still can manually call the `update_fit` function later, without affecting the result.

**Comment by cosama** [comment]
I just realized that from_points does not automatically include (0,0). Is that something we want, otherwise we should add that to the docu string (my preference).

**Comment by jccurtis** [comment]
Let’s add add a keyword for `zero_crossing` or `include_origin` to `from_points`. I could make a quick PR after lunch.

**Comment by cosama** [comment]
Already working on it. I can do that.

**Comment by jccurtis** [comment]
Excellent. Thank you!
