### ISSUE TITLE
Upload becquerel to PyPI

### ISSUE THREAD

**Issue by markbandstra** [lbl-anp/becquerel#119]
We should get this package on the [Python Package Index](https://pypi.org) so that anyone can `pip install` it. There are steps [here](https://packaging.python.org/tutorials/packaging-projects/) for this process.

It looks like we need to do some work on [`setup.py`](https://github.com/lbl-anp/becquerel/blob/61e6b2d0b3c4eba134425e7c17c3fb51990f06c6/setup.py) before we do this:
  - [x] update version number
  - [x] add `maintainer`/`maintainer_email` (this can be me)
  - [x] update `long_description` to read from the README
  - [x] add `long_description_content_type="text/markdown"`
  - [x] fix `url` link (no longer works)
  - [x] fix `download_url` link (no longer works)
  - [x] update `classifiers`
  - [x] add `license` (should this be the text of LICENSE.txt?)
  - [x] try `packages=setuptools.find_packages()`
  - [x] add any other relevant [`setup()` arguments](https://packaging.python.org/guides/distributing-packages-using-setuptools/#setup-args)

In addition, we should add a description to the top of the README of what `becquerel` is and what is its purpose. (Right now it just starts with installation instructions.)

Should we coordinate this with a new tagged release, say version 0.2?

**Comment by jccurtis** [comment]
Thanks for putting this together @markbandstra! I agree that this should go along in v0.2.0 along with the fitting module.

**Comment by cosama** [comment]
Yeah, great work getting that started. I think it is a good idea to make the software easier accessible, but I think we should try to first get at least rebinning (#78), maybe also autocalib (#118) working. I consider those two to be essential for some basic spectroscopy user cases.

**Comment by chunhochow** [comment]
If we move to v1.0 we might trigger the IPO process.

**Comment by jccurtis** [comment]
FYI you can install with:

```bash
pip install git+https://github.com/lbl-anp/becquerel
```
