### ISSUE TITLE
Allow Spectrum counts calculation from cps and livetime

### ISSUE THREAD

**Issue by jccurtis** [lbl-anp/becquerel#122]
As pointing out by @cosama, we currently cannot calculate `Spectrum.counts` from `Spectrum.cps` and `Spectrum.livetime`. This is not symmetric with the corresponding `Spectrum.cps` calculation. This should be a quick patch with a test to assure functionality.

**Comment by markbandstra** [comment]
@jccurtis Implement this with a warning.
