### ISSUE TITLE
Clear up requirements.txt

### ISSUE THREAD

**Issue by cosama** [lbl-anp/becquerel#127]
Currently it seems in the the requirements.txt there are a few modules not used anymore:
* beautifulsoup4
* html5lib
* lxml

They should be removed if not needed.

Furthermore, with little efforts we could remove the following modules:
* future (only used once for viewitems which can be used by simply calling dict.item(), not 100% the same but close enough for what we need)
* six (only required for string_types, can be replaced with what I have added in #126 to utils.py:
```
try:
    isinstance("", basestring)
    def isstring(s):
        return isinstance(s, basestring)
except NameError:
    def isstring(s):
        return isinstance(s, str)
```
* From scipy we only use interp1d, which could be replaced with the function I implemented in the energycal test.

On the other side, I'm not sure if we actually have all modules really used included in requirements.txt. So far I can see additional imports for (I think all standard modules):
* os
* abc
* copy 
* datetime
* struct
* warinings
* builtins (I think this actually calls future.builtins)
* collections
* glob

I was actually wondering if there is a good reason for the `future.builtins` imports? It seems all it does is replace `super(classname, self)` calls with the simpler python3 syntax `super()`, however the earlier works in python3 too.

**Comment by jccurtis** [comment]
Wow, nice dive @cosama! Quick thoughts:

- `lxml` is a faster xml/html parser which will be needed for N42 parsing. `beautifulsoup4` can use it to parser html/xml
- `html5lib` - I'm not sure if the `requests` library uses this but @markbandstra will have more input from the web queries side
- `future` - do we not use this for `true_divide` anywhere? We could drop this as well.
- `scipy` - needed for fitting interface to `MINPACK` and other fitting functions
- `six` - I'm fine dropping it for now but there are other useful tools in `six` which which may want in the future. It is only one file (small lib) and writing py2/3 compatible code becomes more complex without it especially when dealing with `str` vs `bytes` vs `unicode`

Python2/3 builtins (your whole list) ✅:
- `os`
- `abc`
- `copy`
- `datetime`
- `struct`
- `warnings`
- `builtins` (`future.builtins` in py2)
- `collections`
- `glob`

**Comment by jccurtis** [comment]
Also I haven't used `future.builtins` that much. When I want to write compatible code I use the (ugly) form `super(classname, self)`

**Comment by cosama** [comment]
@jccurtis: Thanks for that list, you have some very useful information there. In general I don't mind having external dependencies, but if we don't use them we should remove them, adding them back in is always easy once we need them again.

I am a bit reluctant about the `future` issue as well. It doesn't seem to do much anymore with >=python 2.6, but I'm not sure how this was on older versions. Is there a point in trying to support slightly older python versions? I haven't seen the `true_divide` anywhere though, but might have easily missed it.

I didn't know six was that small, I like that :). My worry is more the additional `pip install` or `apt-get install` required for every additional dependency though, particular for stuff that people don't have installed by default.

Concerning scipy, you are right, I assume the fitting module will be relying heavily on it, so we should just keep it for now.

I can see why the html module might be important for N42 support and other applications, however as long as it is not implemented (which probably won't be the case for the 0.2 release) we should just drop them for now.

**Comment by markbandstra** [comment]
For completeness, these three libraries are optional dependencies for the `pandas` HTML parsing we use:
* `beautifulsoup4`
* `htmlib5`
* `lxml`

The [`pandas` installation instructions](https://pandas.pydata.org/pandas-docs/stable/install.html#dependencies) explain this:
> BeautifulSoup4 and html5lib (Any recent version of html5lib is okay.)
> BeautifulSoup4 and lxml
> BeautifulSoup4 and html5lib and lxml

> Warning: if you install BeautifulSoup4 you must install either lxml or html5lib or both. read_html() will not work with only BeautifulSoup4 installed.

See also #63, #64, #68, and #72 (specifically commit d8a36dd02) for more details.

**Comment by markbandstra** [comment]
I for one am a fan of using `future` because it means that the only difference between Python2 and Python3 code is `from builtins import ...`, otherwise the code is pure Python3. (Unless I'm mistaken.)

I also really dislike the ugly `super` notation that Python2 requires, I much prefer `super()`.

**Comment by cosama** [comment]
I think @markbandstra brought up a good point. In that case we should however try to write as close to python3 code as possible and make full use of `future`. For example it also allows for 
```
from __future__ import unicode_literals
from builtins import str
```

and then in python2 `isinstance(a, str)` is valid code. I think it also has backwards compatible layers for `unicode` and other common python2 vs python3 issues (see http://python-future.org/compatible_idioms.html). Thus we would not really on six and can write python3 style code all the way.

**Comment by cosama** [comment]
By the way with @marbandstra's nice outline about the use of the html libraries and bf4 I think we can close this issue as no changes to requirements.txt is needed?

**Comment by jccurtis** [comment]
Do you want to remove six?

**Comment by jccurtis** [comment]
@cosama will remove `six`
