### ISSUE TITLE
Fit weights for energycal models

### ISSUE THREAD

**Issue by cosama** [lbl-anp/becquerel#133]
Should we allow for weights being provided to calls such as `q.LinearEnergyCal.from_points([230, 400], [1460, 2614])` in order to control the fit. If we have more trust in one peak than another (weights could be based on total counts or FWHM values extracted during a fit) then that might be useful.

It is possible to do that outside of bequerel at this point and then just initialize a calibration object from the `from_coeffs` method, but I think that would be a small enhancement that might be used every now and then.

If we should implement that, then we should do it before we add more models such as proposed in #99 and might break all those models with such a change.

If we won't implement it in at all then @markbandstra  could add an example doing something like that into #132.

**Comment by jccurtis** [comment]
We should use the fitting module #50 base models for these fits instead of `np.polyfit`. This will add more consistency in the tools and allow a high degree of constraints to the fit. `np.polyfit` does allow weights but I think the fitting module will be easier to implement with kwargs.

**Comment by jccurtis** [comment]
Waiting until fitting module (#50) is more complete to implement

**Comment by markbandstra** [comment]
This issue has been addressed somewhat by the new `Calibration` class in #248. Okay to close or keep open?

**Comment by jvavrek** [comment]
> This issue has been addressed somewhat by the new `Calibration` class in #248. Okay to close or keep open?

Probably OK to close, unless you think there are any features missing.
