### ISSUE TITLE
Parser warning for calibration

### ISSUE THREAD

**Issue by jccurtis** [lbl-anp/becquerel#159]
This `warning`:

```python
becquerel/parsers/spectrum_file.py:122: UserWarning: Ignoring calibration; energies not monotonically increasing
```

should be a `ParserWarning`

**Comment by cosama** [comment]
Good catch. Looking at the code I actually think the message is confusing. In the end it means that the created spectrum won't have the `bin_edges_kev` attribute populated, however I would not get that from the message, I would not even expect the entire calibration being an issue, maybe just a bin or something. Also the code is not that clear, the`if` statement in `spectrum.py` on line `454` actually takes care of this, kind of far removed from where the `warning` is raised. Maybe we should set `self.energy_bin_edges = None` to make this a bit more explicit in `spectrum_file.py` and then check for that property instead and change the `warning` message to something more explicit.

**Comment by cosama** [comment]
Is there a reason for the `energy_bin_widths` attribute in `class SpectrumFile`. I don't find it anywhere being used and it is kind of redundant information.

**Comment by jccurtis** [comment]
Re: `energy_bin_widths` I think this was added as a convenience attr
Re: parsing, you are absolutely right and we need to rewrite the parsers as in #103
