### ISSUE TITLE
XCOM format change

### ISSUE THREAD

**Issue by jccurtis** [lbl-anp/becquerel#167]
Something (probably small) has changed in the XCOM return format. Travis fails on `py27` and `py36`. I have local failures in `py37`.

See [this build](https://travis-ci.org/lbl-anp/becquerel/builds/474229506) for more details and error tracebacks.

**Comment by jccurtis** [comment]
Wait, this is due to the federal government shutdown ...

This brings up the recurring idea to cache all the XCOM data locally as captured in #104. I'm closing this for now ...

**Comment by markbandstra** [comment]
Can we change the title of this issue for future clarity? Like, XCOM/NIST data tends to fail if the federal government shuts down? (NNDC is probably fine right now since it's DOE.)

**Comment by jccurtis** [comment]
Good idea, done!
