### ISSUE TITLE
Improve support for ROI block in SPE files

### ISSUE THREAD

**Issue by jasonmhite** [lbl-anp/becquerel#181]
SPE files support a block called `$ROI`, which is meant for listing regions of interest within the spectrum. The current implementation in becquerel doesn't actually parse this block, it just stores the raw lines as strings. I'd like to extend support to properly parse this block into a list of tuples, where each tuple is a pair containing the beginning and end channel for each ROI. 

I don't think anybody actually uses this block in practice and current support even if your file does include ROIs is not reliable since it does not get parsed at all. My main reason for supporting it is to make writing unit tests for #179 easier, so that I can pass in ROIs in a reasonable format instead of having to stringify them. 

My implementation of the SPE file writer I'm working on for #179 already includes the fix (which is pretty minor), but I will also backport it to `SpeFile._spe_format` and `SpeFile.read`.

**Comment by jccurtis** [comment]
@jasonmhite just following up on old issues. Did you put together a refactored spe parser?

**Comment by jasonmhite** [comment]
@jccurtis partially, but I ended up getting too busy to quite polish it. Maybe I can go dust it off if there is still interest?

**Comment by jccurtis** [comment]
Good to hear from you! Yeah definitely. Even if you just open a PR we could branch off of it and finish it up if you don't have the time. Even if the PR is just a quick fix for the ROI section. The parser refactor is a much larger effort which we need to think about ...

**Comment by markbandstra** [comment]
@jasonmhite In case it would be helpful, I am in the process of adding full read/write support for spectra using the HDF5 format, and it will also store the calibration information. If you already have the SPE format I/O working then this might not be as useful to you, but just FYI it's #244.
