### ISSUE TITLE
Spectrum should take list-mode data

### ISSUE THREAD

**Issue by jvavrek** [lbl-anp/becquerel#183]
It'd be nice to create a Spectrum object from list-mode data such as an `np.array()` or from a (possibly time-stamped) plaintext file of ADC values. (See also #116.) This mostly just saves the user the step of calling
`bin_contents, bin_edges = np.histogram(data, nbins, erange)`
before
`bq.Spectrum(counts=bin_contents)`
but it should be integrated into Becquerel.

**Comment by jccurtis** [comment]
Quick solution (untested):

```python
# after Spectrum.__init__ definition
@classmethod
def from_listmode(cls, adc_channels, timestamps=None, bins=None):
    if bins is None:
        bins = np.arange(0, np.ceil(max(adc_channels)), dtype=np.int)
    bin_counts, bin_edges = np.histogram(adc_channels, bins=bins)
    kwargs = {'counts': bin_counts}
    if timestamps is not None:
        # How do we handle these? This isn't accurate ...
        # What are the timestamps: 'float', 'int', 'datetime', epoch [nano][micro][milli]seconds?
        kwargs['start_time'] = min(timestamps)
        kwargs['stop_time'] = max(timestamps)
        kwargs['livetime'] = kwargs['stop_time'] - kwargs['start_time']
    return cls(**kwargs)
```

This needs to support:
* passing energies directly
* better timestamp handling ... this won't work for time since acquisition start ...
* better livetime/realtime handling

Thoughts?

**Comment by jccurtis** [comment]
Also, this is strongly linked with #184 as mentioned by @jvavrek since we should be able to pass a separate `bin_edges_adc` for un-calibrated data which doesn't yet have `bin_edges_keV`

**Comment by jvavrek** [comment]
- My ROOT is showing, but I think a `from_listmode()` histogramming method should take also take an xmin and an xmax. These can default to 0 and the max channel as above if not specified.
- I would rename `adc_channels` in the above snippet. It's not immediately clear that it's the list mode data.
- I'm also unsure on the timestamp handling, as the start/end acquisition times are generally not the first/last timestamps
- Do we need two variables `bin_edges_adc` and `bin_edges_keV`, or can we just make a single more general `bin_edges` with implied units that gets updated after calibration?

**Comment by jccurtis** [comment]
1. That is implicitly supported with the `bins` kwarg to nump histogram which is the `bin_edges` if an array or the number of bins if a scalar (with the default min/max assigned based on the data). Maybe `bin_edges` is a better naming for `bins` and don't allow passing a scalar?
2. ✅ 
3. 🤷‍♂ 
4. Worth a conversation, I think just `bin_edges` would lead to confusion. Additionally, do you just lose the `adc_value` information?

**Comment by jvavrek** [comment]
1. Passing a scalar is very useful, especially if `np.histogram` handles scalars and arrays automatically. See branch `issue-list-mode` for how I currently do it based on the above code.
4. Keeping both `bin_edges_kev` and `bin_edges_adc` is better, now that I think about it. Adding the latter to the codebase will probably require a fair bit of work, so I'll leave it to someone more familiar with the code. For now, branch `issue-list-mode` sets `bin_edges_kev` as a workaround.
