### ISSUE TITLE
Issue connecting to `physics.nist.gov`

### ISSUE THREAD

**Issue by cosama** [lbl-anp/becquerel#185]
I have some issues connecting to `physics.nist.gov` recently. It could be related to my dns setup (I use `opendns` if I remember correctly), but it could also be related to changes on nist. I can access the database on `pmlb.nist.gov`. If somebody else has issues:

```
sed -i 's/physics.nist.gov/pmlb.nist.gov/g' becquerel/tools/materials.py
sed -i 's/physics.nist.gov/pmlb.nist.gov/g' becquerel/tools/xcom.py
```
in the becquerel source directory fixed it for me.

**Comment by jccurtis** [comment]
Both route to `https://www.nist.gov/pml` for me. I cannot `ping` either of them though ...

I actually can't ping `nist.gov` but I did learn that NIST runs on AWS:

```
$ ping www.nist.gov
PING dualstack.mc-12555-1019789594.us-east-1.elb.amazonaws.com (54.210.139.30): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
```

**Comment by cosama** [comment]
Now `physics.nist.gov` is working again. Maybe a dns cache issue.

**Comment by jccurtis** [comment]
Ready to close?

**Comment by cosama** [comment]
Has happened a couple of time. Lets keep it open for a bit and see if someone else runs into this.

**Comment by jccurtis** [comment]
Have you encountered this again?

**Comment by cosama** [comment]
No but haven't used it a lot. I will close this for now.
