### ISSUE TITLE
Electron range calculations and lookups

### ISSUE THREAD

**Issue by bplimley** [lbl-anp/becquerel#21]
I have code that uses Tabata's analytical formulae for electron CSDA and extrapolated ranges. It's old code, so it needs cleanup. I'd like to add web queries for NIST ESTAR (electron stopping powers and ranges). ESTAR doesn't give extrapolated ranges, and only gives CSDA ranges for their default grid energies, which is why Tabata is useful.

I'm making this issue to remind myself to work on this later.

**Comment by jccurtis** [comment]
Closing as won't fix for now
