### ISSUE TITLE
"Feature"/"Peak" class structure

### ISSUE THREAD

**Issue by bplimley** [lbl-anp/becquerel#22]
Base classes / structure for peaks or other spectral features.

**Comment by jccurtis** [comment]
This is related to #50 and should build off the underlying tools to determine the peak/feature shape characteristics. There are a couple ways of doing this which could be addressed when we move towards a more comprehensive energy calibration workflow

**Comment by jccurtis** [comment]
Closing for now as superseded by #50 and will be integrated in the ecal tools
