### ISSUE TITLE
Initial guess of fitting can be improved for Gaussian

### ISSUE THREAD

**Issue by cosama** [lbl-anp/becquerel#225]
The intial guess for fitting seems to be off by about a factor of 2 or so for the gaussian case. I never managed to track this down, but I assume it is related to some normalization with the bin with or a factor of `2*pi`.

**Comment by jvavrek** [comment]
This might be a bit redundant with #219.

Anyway, for the Gaussian in particular, we currently guess the amplitude as just the sum of all (normalized) bins in the ROI, which can be heavily influenced by a high background far from the peak centroid.
```
amp = np.sum(y[msk]/dx[msk])
```

I suggest instead:
```
sigma = xspan * width_ratio / 10.  # existing sigma guess
amp = np.max(y[msk]) * np.sqrt(2*np.pi) * sigma  # new amplitude guess
```

(this might not work well in somewhat pathological cases where the background is higher than the peak at edge(s) of the ROI, but then I suspect the sum method won't either)

Anyway, here's the current sum method:
![image](https://user-images.githubusercontent.com/7683814/104533806-ea23ce00-55c7-11eb-8b4d-c2619047ca68.png)

And here's my proposed method:
![image](https://user-images.githubusercontent.com/7683814/104533910-1ccdc680-55c8-11eb-801a-eceb8a847db7.png)

It certainly looks better, but strangely, the number of function evals in the minimizer is higher in the second case...

**Comment by cosama** [comment]
Could it be that we actually get the right initial value but it is plot wrong? I agree that it is overestimated if there is a background, but I have observed that it is also looks overestimated when there is no background at all, at least on the graph.

**Comment by cosama** [comment]
Just checked and the code seems fine plotting it. It is using the same calls as the model graph.

**Comment by jvavrek** [comment]
> 
> 
> Could it be that we actually get the right initial value but it is plot wrong? I agree that it is overestimated if there is a background, but I have observed that it is also looks overestimated when there is no background at all, at least on the graph.

Do you have an example of overestimation with no background handy?

**Comment by cosama** [comment]
Looks like I was wrong again:

```
x = np.arange(0, 200)
y = bq.core.fitting.gauss(x, 100, 100, 10)
plt.figure()
plt.plot(x, y)
fitter = bq.Fitter(
    ['gauss', 'constant'],
    x=x,
    y=y,
    y_unc=1/np.sqrt(y + 1),
    roi=(0, 200)
)
fitter.fit()
print(fitter.result.init_values)
fitter.custom_plot();
```

![gausstest](https://user-images.githubusercontent.com/7439971/104547470-7db6c800-55e3-11eb-8b2d-ef9f8105e9dd.png)

Really can't remember what I was trying to do. I would suggest:

```
bkg = (y[-1]/dx[-1] + y[0]/dx[0])*0.5 * dx
amp = np.sum(y - bkg)
```
as the initial guess.

**Comment by jvavrek** [comment]
> Seems to not do particular well for the exponential decay you are showing though.

Can you show that plot?

**Comment by cosama** [comment]
Never mind, it actually just worked above because the bin_size was 1.

```
bin_size = 0.5
x = np.arange(0, 200, bin_size)
y = bq.core.fitting.gauss(x, 10000, 100, 10)
dx = np.ones(len(y)) * bin_size
plt.figure()
plt.plot(x, y)
fitter = bq.Fitter(
    ['gauss'],
    x=x,
    y=y,
    y_unc=1/np.sqrt(y + 1),
    roi=(0, 200)
)
fitter.fit()
print(fitter.result.init_values)
fitter.custom_plot();
```
![gausstest](https://user-images.githubusercontent.com/7439971/104549318-814c4e00-55e7-11eb-93c9-8525db4d61d6.png)


@jvavrek I added it to the previous comment.

**Comment by jvavrek** [comment]
@cosama so that I have all the options correct: this tells us that the existing guess for the amplitude performs poorly when the bins are not all 1?

**Comment by jvavrek** [comment]
The `bin_size = 0.5` example suggests we're guessing twice the real amplitude, i.e., dividing by `dx = bin_size = 0.5` where we don't need to.

**Comment by cosama** [comment]
Yeah, but looking at the code it seems fine, not sure why this is the case. Maybe we have to initialize it with `amp = np.sum(y[msk])` instead of `amp = np.sum(y[msk]/dx[msk])`?

**Comment by jvavrek** [comment]
> Maybe we have to initialize it with amp = np.sum(y[msk]) instead of amp = np.sum(y[msk]/dx[msk])?

I think you're correct here, since the curve should have the same units as the histogram. If we increase the bin size by a factor of 2, thereby increasing the counts per bin by a factor of 2, the amplitude should also increase by a factor of 2. It is only in the final step when we want to interpret the number of counts in terms of the amplitude that we need to divide by `dx`.

**Comment by cosama** [comment]
@jvavrek Yeah when I implemented `dx` I think I made an error of thought. `amp` is the integrated number of counts. The normalization by bin with is included in `sigma` So I think we have to remove the `dx` there which means that the initial guess actually won't depend on `dx` at all.

**Comment by jvavrek** [comment]
@cosama We should write a test or at least a notebook example for this:
 - [ ] sample a gaussian say 10000 times, compute guesses at various binwidths, ensure they change as expected, and ensure that the final `amp/dx` or whatever is close to 10000

**Comment by jvavrek** [comment]
> So I think we have to remove the `dx` there which means that the initial guess actually won't depend on dx at all.

Agreed. The fit routines just see `x` and `y` and are agnostic to binwidths.

**Comment by jvavrek** [comment]
Another nice feature I just thought of:
- [ ] add error bands to the plot around the fit result

I don't know offhand how to define ±1 sigma error bands when you have multiple fit parameters... to be determined.

**Comment by jvavrek** [comment]
> Another nice feature I just thought of:
> 
> * [ ]  add error bands to the plot around the fit result
> 
> I don't know offhand how to define ±1 sigma error bands when you have multiple fit parameters... to be determined.

https://lmfit.github.io/lmfit-py/model.html?highlight=modelresult#calculating-uncertainties-in-the-model-function

**Comment by jvavrek** [comment]
Note this will also trickle down to `gausserf`, for example:
<img width="514" alt="Screen Shot 2021-02-26 at 12 47 02 PM" src="https://user-images.githubusercontent.com/7683814/109353216-e8892f00-7830-11eb-8bc1-1a2c81b9433c.png">
