### ISSUE TITLE
IsotopeQuantity has a kwarg `date` that cannot be a `datetime.date` object

### ISSUE THREAD

**Issue by jvavrek** [lbl-anp/becquerel#226]
The kwarg `date` in IsotopeQuantity (and its docstring) suggest that a `datetime.date` object should work, but it won't:
(note for posterity that the actual calibration date of this source is Apr 1, 2019)
```
>>> bq.IsotopeQuantity('Cs-137', uci=189.6, date=datetime.date(2020, 11, 5))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-90-1eb84c4f3676> in <module>
----> 1 bq.IsotopeQuantity('Cs-137', uci=189.6, date=datetime.date(2020, 11, 5))

~/becquerel/becquerel/tools/isotope_qty.py in __init__(self, isotope, date, stability, **kwargs)
     99 
    100         self._init_isotope(isotope, stability)
--> 101         self._init_date(date)
    102         self._ref_quantities = self._quantities_from_kwargs(**kwargs)
    103 

~/becquerel/becquerel/tools/isotope_qty.py in _init_date(self, date)
    129 
    130         self.ref_date = utils.handle_datetime(
--> 131             date, error_name='IsotopeQuantity date', allow_none=True)
    132         if self.ref_date is None:
    133             # assume a long-lived source in the current epoch

~/becquerel/becquerel/core/utils.py in handle_datetime(input_time, error_name, allow_none)
    130     else:
    131         raise TypeError(
--> 132             'Unknown type for {}: {}'.format(error_name, input_time))
    133 
    134 

TypeError: Unknown type for IsotopeQuantity date: 2020-11-05
```

Instead it requires a`datetime.datetime` object, i.e., an additional time specification. Can we just set the time to 12 noon like I think most of these sources do, and maybe throw a warning when doing so?

**Comment by jvavrek** [comment]
In addition, it could be useful for all the `_at()` methods to have a default `date` of now:
```
import datetime
>>> datetime.datetime.now()

datetime.datetime(2021, 2, 18, 14, 5, 42, 625840)
```

**Comment by jvavrek** [comment]
Thoughts on this one @cosama ?

**Comment by cosama** [comment]
Yeah that sounds reasonable. 

On construction we can just test if it is a date object `isinstance(date, datetime.date)` and then create a datetime object with `date = datetime.datetime(date.year, date.month. date.day)`.

Also we would need a few updates to the doc strings.

Want to put in a merge request? This should be quick.

**Comment by jvavrek** [comment]
> Want to put in a merge request? This should be quick.

Yeah, will do
