### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by jccurtis** [lbl-anp/becquerel#243]
We currently don't support python3.9 explicitly because of missing pypi wheel support for [llvmlite](https://github.com/numba/llvmlite/issues/669). Python3.9 will be supported by [numba](https://github.com/numba/numba/pull/6685) very soon (currently in beta). That said, you still need to compile `llvmlite` yourself. For now, becquerel does not officially support python 3.9 but it will likely work if you can install `numba` and `llvmlite`.

**Comment by cosama** [comment]
We do support python3.9 for a while now. Closing
