### ISSUE TITLE
`Spectrum` rebinning

### ISSUE THREAD

**Issue by bplimley** [lbl-anp/becquerel#29]
* Rebinning according to an input bin edges vector
* `rebin_like(spec)` to use the binning from another spectrum

Please expand on this, I'm not very familiar with rebinning methods or needs.

**Comment by chunhochow** [comment]
Todo:
- [ ] Binomial sampling option (keyword argument)
- [ ] auto fit linear spline (keyword arg)
- [ ] auto fit higher-order spline? (with a Sav-Gol filter?)
- [ ] write tests

**Comment by thjoshi** [comment]
@chunhochow @jccurtis when is rebinning coming to Spectrum?  I was trying to use Becquerel last week for a project and was quite surprised to find that any form of rebinning wasn't in the primary branch.  If additional features come later that makes sense, but in my view there should be a basic functionality already.
