### ISSUE TITLE
ErfModel fails unless coupled to a GaussModel

### ISSUE THREAD

**Issue by jvavrek** [lbl-anp/becquerel#305]
The `guess()` method of `ErfModel` defines its guess for its `sigma` parameter by looking for an existing parameter called `gauss_sigma`:
```py
(f"{self.prefix}sigma", "expr", "gauss_sigma")
```

But if your peak is an `expgauss`, then it won't find anything, and it'll error out. Is there a more robust guess we can use?

Tagging @cosama

**Comment by cosama** [comment]
That was not intended to be like that. We especially moved to a `GaussErfModel` to be able to couple the two. They were separated earlier in the development of the fitting module, but we thought it was odd to have it coupled. 

I would use a guess similar to the gaussian case:

```
sigma = xspan * width_ratio / 10.0
```

with an additional arguement to the `guess` function of something like `width_ratio=0.5`.

Side note: Not sure about that factor of 10. That seems kind of a random choice as well, it could (should?) just be absorbed into the width_ratio. If I hear with ratio I would not guess that it will be divided by 10 for some reason.

I can file a merge request later.
