### ISSUE TITLE
Incompatibility between calibration and parsers when calibrated energies can be negative

### ISSUE THREAD

**Issue by jvavrek** [lbl-anp/becquerel#309]
Often we can end up with negative calibrated energies, e.g., in the first few bins if the calibration linear term is negative. These are clipped to zero by default in the new calibration module. However multiple zero edges will throw an error that the bin edges are not monotonically increasing.

One can normally change the clipping on the domain and range when doing calibrations manually, but not so with parsers, which automatically apply the calibration. One cannot change the clipping ranges passed into the calibration methods because the `DEFAULT_DOMAIN` etc are passed to those methods when the module is _imported_, not when the function is called.

We could either provide more kwargs to the parsers to prevent this, or allow negative energies (i.e., broaden or remove the clipping).

**Comment by werthm** [comment]
I agree, this is an issue for me as well. DEFAULT_RANGE should allow negative energy values as well.

**Comment by jvavrek** [comment]
I believe @markbandstra is working on this in #319

**Comment by markbandstra** [comment]
Closed by #319
