### ISSUE TITLE
Calibration should raise a warning if it needs to clip to its range

### ISSUE THREAD

**Issue by markbandstra** [lbl-anp/becquerel#314]
A few times in practice a situation like the following has come up:

```python
import becquerel as bq
spec = bq.Spectrum.from_file("tests/samples/nai_detector.spe")
cal = bq.Calibration.from_linear([-10, 2.02])
spec.apply_calibration(cal)
```

And the result is that the `Spectrum` raises a `ValueError`:

```
ValueError                                Traceback (most recent call last)
Input In [22], in <module>
----> 1 spec.apply_calibration(cal)

File becquerel/becquerel/core/spectrum.py:1151, in Spectrum.apply_calibration(self, cal)
   1144     warnings.warn(
   1145         "The use of bq.EnergyCalBase classes is deprecated "
   1146         "and will be removed in a future release; "
   1147         "use bq.Calibration instead",
   1148         DeprecationWarning,
   1149     )
   1150 except AttributeError:
-> 1151     self.bin_edges_kev = cal(self.bin_edges_raw)
   1152 self.energy_cal = cal

File becquerel/becquerel/core/spectrum.py:535, in Spectrum.bin_edges_kev(self, bin_edges_kev)
    533     raise SpectrumError("Bad length of bin edges vector")
    534 elif np.any(np.diff(bin_edges_kev) <= 0):
--> 535     raise ValueError("Bin edge energies must be strictly increasing")
    536 else:
    537     self._bin_edges_kev = np.array(bin_edges_kev, dtype=float)

ValueError: Bin edge energies must be strictly increasing
```

The issue is that for the first few channels near zero, the calibration curve produces a negative output, and it implicitly clips it to the default range of `0` to `1e5`. So when the `Spectrum` sees that the first few channels have zero width in energy space, it raises this error.

This error is confusing because it doesn't point directly to the culprit -- that the calibration parameters need to be adjusted, or the calibration range needs to be extended -- and instead can lead to wasted time looking around `Spectrum`.

One solution would be to have `Calibration` raise an error if it goes out of range, but that outcome was considered and not favored when writing it because then fitting would become more complicated by often raising errors while searching for good parameter fits. Instead, it would be helpful for it to at least raise a warning so that this error can be more quickly understood, and for that warning to note that a `ValueError` might follow from `Spectrum`.

The range clipping is performed in this line:

https://github.com/lbl-anp/becquerel/blob/main/becquerel/core/calibration.py#L132

**Comment by markbandstra** [comment]
To be clear, the solution is to simply provide a wider `rng` when creating the `Spectrum`:

```python
import becquerel as bq
spec = bq.Spectrum.from_file("tests/samples/nai_detector.spe")
cal = bq.Calibration.from_linear([-10, 2.02], rng=[-10, 1e5])
spec.apply_calibration(cal)
```

And no error is raised. And the warning would be to point the user to this solution.

**Comment by jvavrek** [comment]
As mentioned this is also an issue for `Spectrum.from_file(), because it doesn't currently accept an `rng` kwarg that can be passed into the parser:
```py
# spectrum.py
@classmethod
def from_file(cls, infilename, verbose=False):
    ...

# cnf.py
def read(filename, verbose=False):
    ...
```

**Comment by markbandstra** [comment]
@jvavrek good point. Would it be helpful (to too complicated) to pass a `cal_rng` kwarg or something of the sort to `from_file`? Otherwise we could just make the default `rng` extremely generous, but that has its own problems.

**Comment by jvavrek** [comment]
> @jvavrek good point. Would it be helpful (to too complicated) to pass a `cal_rng` kwarg or something of the sort to `from_file`? Otherwise we could just make the default `rng` extremely generous, but that has its own problems.

Maybe a generic `**cal_kwargs`?
