### ISSUE TITLE
Efficiency calibration

### ISSUE THREAD

**Issue by bplimley** [lbl-anp/becquerel#32]
Energy-dependent detector efficiency calibration.

~The basis for this (having peaks with a net area and assigning a calibration value) should be in my upcoming pull request for energycal and peaks. But it will take some expanding, probably along the lines of the (upcoming) energycal design.~

**Comment by markbandstra** [comment]
Such a calibration can be captured with the new `Calibration` class (#248), but it is not yet integrated into `Spectrum` in any way.
