### ISSUE TITLE
Flaky NNDC tests failing

### ISSUE THREAD

**Issue by jccurtis** [lbl-anp/becquerel#332]
We still have the flaky tests failing in the CI. See this [pipeline](https://github.com/lbl-anp/becquerel/runs/5779050487?check_suite_focus=true)

- [x] Add to dev requirements

**Comment by jvavrek** [comment]
Those tests are indeed marked with `flaky` but it's possible they failed all three times if the NNDC server was down for a few seconds:
```py
@pytest.mark.flaky(reruns=3)
class TestDecayRadiationQuery(NNDCQueryTests):
```

**Comment by jccurtis** [comment]
@jvavrek can we all a timeout between reruns?

**Comment by jvavrek** [comment]
Oh and the package is not `pytest-flaky` but [`pytest-rerunfailures`](https://github.com/pytest-dev/pytest-rerunfailures), which is in `requirements-dev.txt`.

**Comment by jccurtis** [comment]
Maybe we can add the following to try three times with a 2 second delay only for 

```python
@pytest.mark.flaky(reruns=3, reruns_delay=2, only_rerun=NNDCRequestError)
```

(Not sure on the only_rerun syntax - it might need to be a string or a list of exceptions.)

**Comment by jvavrek** [comment]
> Maybe we can add the following to try three times with a 2 second delay only for
> 
> ```python
> @pytest.mark.flaky(reruns=3, reruns_delay=2, only_rerun=NNDCRequestError)
> ```
> 
> (Not sure on the only_rerun syntax - it might need to be a string or a list of exceptions.)

I don't think that's supported yet: https://github.com/pytest-dev/pytest-rerunfailures/issues/164
