### ISSUE TITLE
Spectrum plotting

### ISSUE THREAD

**Issue by bplimley** [lbl-anp/becquerel#37]
Methods in `Spectrum` for plotting. Visualization is not a main focus, but at least basic plotting with some common options.

Some ideas:
* use `drawstyle='steps-mid'` for "stairs"-type plot
* log y-scale by default
* automatically label axes
* color, legend label, title
* allow plotting into an existing axes

**Comment by cosama** [comment]
I just submitted the newest version, it includes errorbars/bands too. Have a look, if it is good I can send out the pullrequest.

**Comment by cosama** [comment]
Merging pull request #114 closes this issue.
