### ISSUE TITLE
Consider moving all linting and formatting to ruff

### ISSUE THREAD

**Issue by markbandstra** [lbl-anp/becquerel#397]
It appears that [`ruff`](https://docs.astral.sh/ruff/) has become the new standard for linting and formatting code, and it is incredibly fast. [Various prominent projects are already using ruff](https://github.com/astral-sh/ruff?tab=readme-ov-file#whos-using-ruff), and we should consider it.

I noticed that one common tool, [`pydocstyle`](https://github.com/PyCQA/pydocstyle), recently became retired and now [points to ruff as a replacement](https://github.com/PyCQA/pydocstyle?tab=readme-ov-file#ruff-a-modern-alternative).

**Comment by jccurtis** [comment]
Hey @markbandstra, need some help with this?

**Comment by markbandstra** [comment]
Hi @jccurtis ! Sure, I was having trouble today figuring out exactly what is going wrong with the tests on #398, so if you have spare cycles, that would be helpful!

**Comment by markbandstra** [comment]
Actually I ended up figuring the problem out, it was a subtlety in using `pytest-ruff`.
