### ISSUE TITLE
How to present example code

### ISSUE THREAD

**Issue by bplimley** [lbl-anp/becquerel#49]
Clearly, an important part of usability is having example code for people to see how Becquerel works.

There are several possible approaches to this, at least:
* code snippets in docstrings (as in `spectrum.py` and `energycal.py`)
* scripts in `examples` directory (as in #16)
* Jupyter notebooks
* code as part of HTML documentation (like Sphinx; see #18)

Comments:
* Docstrings: preferably not more than 2-4 lines of code
* Scripts in `examples`: this works for longer, standalone examples
* Jupyter notebooks: maybe "nicer" than example scripts, allowing comments with markdown, inline plots, etc. @jccurtis suggested this a while back.
* HTML documentation: maybe this would be more along the lines of docstring examples, as part of explaining how the code works. But more extensive examples might not belong in HTML docs.

The examples can always be moved into different formats later. But what should our near-term approach be?

**Comment by markbandstra** [comment]
We have been using notebooks.
