### ISSUE TITLE
Contributor License Agreement assistant

### ISSUE THREAD

**Issue by chunhochow** [lbl-anp/becquerel#70]
Something like this might be helpful if we want external contributors to explicitly have to press "Agree" to our licensing language or leave information before their pull request clears all checks.
https://cla-assistant.io/
https://github.com/cla-assistant/cla-assistant

**Comment by chunhochow** [comment]
This actually requires us to host a server to host the site where people sign the agreement. It's doable, but would require some work and is probably less than ideal for us.

**Comment by jccurtis** [comment]
@chunhochow It looks like you can use the free hosted instance (from SAP) at https://cla-assistant.io which stores data in an `mLab` database. I'm not sure if this would be permanent solution. We could host the service but the upkeep is likely outside our current scope. 😄

**Comment by chunhochow** [comment]
Ignored for now
