### ISSUE TITLE
SPE File Parser $ENDRECORD

### ISSUE THREAD

**Issue by jccurtis** [lbl-anp/becquerel#81]
Whenever I convert a file with PeakEasy to an SPE file it adds a line at the end of the file (with nothing following):

```
$ENDRECORD:
```

This prints a warning:

```
Unknown line:  $ENDRECORD:
```

I think this line is a generic metadata tag to contain other information that cannot be natively saved within a `SPE` file (i.e. when converting a more complex file like `SPC` or `N42`). 

I propose that we:

- [x] Figure out if this line has other specific meaning in an SPE file (besides my above guess)
- [x] Add the data to a `metadata` or other generic text blob in `Spectrum`

**Comment by markbandstra** [comment]
@jccurtis and I discussed having the parsers raise warnings for this case and analogous cases.

**Comment by jccurtis** [comment]
@markbandstra look at `example-spectra-#20`

**Comment by jccurtis** [comment]
#135 is closed. @markbandstra maybe lets just add these as a dictionary of `metadata`?

**Comment by cosama** [comment]
@jccurtis. Great idea. I really started to appreciate the flexibility of dictionaries in that regards.
