### ISSUE TITLE
Error during CI: "distutils.errors.DistutilsError: Download error for https://pypi.python.org/packages/...: [Errno 99] Cannot assign requested address"

### ISSUE THREAD

**Issue by markbandstra** [lbl-anp/becquerel#83]
There have been 2 or 3 occurrences in the last two weeks of Travis-CI integration tests failing because of the following error (this is a particular instance from 1/7/18, I'm assuming the hashes change):

```
distutils.errors.DistutilsError: Download error for https://pypi.python.org/packages/d1/8a/5f1385bba05d887662835d1230fb9a362c5c03f4f744a4fe0455d9474cf3/pytest_runner-3.0-py2.py3-none-any.whl#md5=25076b14ff1877c02434953044f4f2a8: [Errno 99] Cannot assign requested address
```

Our test configuration is
```json
{
  "language": "python",
  "python": "2.7",
  "install": [
    "pip install --upgrade pip setuptools wheel",
    "pip install --only-binary=numpy,scipy numpy scipy",
    "pip install -r requirements-dev.txt",
    "python setup.py install"
  ],
  "script": "python setup.py test",
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
```

The full log is here: [travis_150_1_log.txt](https://github.com/lbl-anp/becquerel/files/1613251/travis_150_1_log.txt)

**Comment by jccurtis** [comment]
Thanks for logging this @markbandstra, I can download the wheel installer from that exact [url](https://pypi.python.org/packages/d1/8a/5f1385bba05d887662835d1230fb9a362c5c03f4f744a4fe0455d9474cf3/pytest_runner-3.0-py2.py3-none-any.whl#md5=25076b14ff1877c02434953044f4f2a8) which is a bit strange. 

I've noticed that these failed builds also have an earlier error during OS setup which looks like a network connection failure:

```
Executing: /tmp/tmp.3024xXaczv/gpg.1.sh --keyserver
hkp://keyserver.ubuntu.com:80
--recv
EA312927
gpg: requesting key EA312927 from hkp server keyserver.ubuntu.com
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
W: The repository 'https://packagecloud.io/computology/apt-backport/ubuntu trusty Release' does not have a Release file.
W: The repository 'https://packagecloud.io/github/git-lfs/ubuntu trusty Release' does not have a Release file.
W: The repository 'https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty Release' does not have a Release file.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  Could not connect to archive.ubuntu.com:80 (91.189.88.161), connection timed out [IP: 91.189.88.161 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.161 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-backports/InRelease  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.161 80]
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/39x/InRelease  Could not connect to www.apache.org:80 (140.211.11.105), connection timed out
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/InRelease  Could not connect to dl.google.com:80 (172.217.9.206), connection timed out
W: Failed to fetch http://toolbelt.heroku.com/ubuntu/./InRelease  Could not connect to toolbelt.heroku.com:80 (50.19.119.234), connection timed out [IP: 50.19.119.234 80]
W: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/trusty/mongodb-org/3.4/InRelease  Could not connect to repo.mongodb.org:80 (54.230.194.100), connection timed out
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/trusty-pgdg/InRelease  Could not connect to apt.postgresql.org:80 (87.238.57.227), connection timed out [IP: 87.238.57.227 80]
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

The build continues but I think the OS keyserver can't check hashes as a result of the first time out so additional downloads that require the OS GPG auth fail. I haven't been able to find an exactly suitable work around in the Travis docs/github/forums. It is almost like we need to set a global retry number to attempt to retry OS setup. I'm sure someone has solved this. That said, from some searching, potential fixes could include:

- [ ] Wrap the `install` commands in `travis_retry` which will try 3 times for a return code of `0` but this won't fix the earlier initial OS setup failure. 
- [ ] Add a couple commands at the beginning of our `install` which try to download the keys and then `apt-get update/upgrade/etc`

**Comment by markbandstra** [comment]
Appears to be related to this:
https://github.com/travis-ci/travis-ci/issues/9000

**Comment by jccurtis** [comment]
In any case, lets upgrade the build ENV to `xenial`. `bionic` is coming out at the end of April 😄 ...

**Comment by markbandstra** [comment]
It looks like Travis does not offer xenial as a build environment. This limitation is mentioned in various issues, and their [documentation](https://docs.travis-ci.com/user/reference/overview/) only lists precise and trusty.

**Comment by jccurtis** [comment]
Ah yes, thanks @markbandstra! There is a lot of chatter and confusion in the travis GitHub issues regarding the lack of Xenial support. Apparently it (unofficially) worked in Dec for a couple weeks while they were doing some testing.

Additionally all travis builds are currently defaulting to `sudo=required`: https://twitter.com/travisci/status/950481155740127232

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">We will be temporarily routing all sudo: false jobs to the infrastructure we use for sudo: required. You may need to update any IP safelists to include IP ranges for sudo-enabled Linux. You can find them here: <a href="https://t.co/a3kpisQ7V1">https://t.co/a3kpisQ7V1</a></p>&mdash; Travis CI (@travisci) <a href="https://twitter.com/travisci/status/950481155740127232?ref_src=twsrc%5Etfw">January 8, 2018</a></blockquote>

**Comment by markbandstra** [comment]
So should we just wait this out? I would like to avoid setting ```sudo: required```.

**Comment by jccurtis** [comment]
Yeah, lets wait until Xenial is released as a build ENV on Travis which should happen in the next couple of months (since Bionic is coming out on April 26).

I think the current builds should complete as expected because the default ENV is sudo regardless of our setting.

Can you elaborate on your avoidance of using `sudo`? I understand it is not necessary to test `Bq` but it appears to be a way to avoid the network + key retrieval bugs.

**Comment by markbandstra** [comment]
I would like to avoid the `sudo` option in the long run because we don't recommend installing our package with `sudo python setup.py install`, and `sudo` could mask important issues that could come up during installation.

**Comment by jccurtis** [comment]
That sounds good. Lets leave this open until Travis release's a `xenial` build env.

**Comment by jccurtis** [comment]
Additionally, `sudo=false` is now routed correctly so **our builds are NOT using `sudo`**:

https://blog.travis-ci.com/2018-01-08-travis-response-meltdown-spectre

We may see this issue pop up again but I think that is fine for the time being.

**Comment by markbandstra** [comment]
Travis must have fixed this.
