### ISSUE TITLE
CSV Spectrum Input / Output

### ISSUE THREAD

**Issue by jccurtis** [lbl-anp/becquerel#87]
We don't currently have a method to read/write to CSV files

- [ ] check `PeakEasy` for for standard CSV format
- [ ] ???

**Comment by jccurtis** [comment]
Leaving in `v0.3.0` for now. Will revisit. Thoughts @alihanks ?

**Comment by jvavrek** [comment]
As we're moving away from CSV to hdf5 formats and there generally isn't a _standard_ CSV format, I vote to close. The user can always use `np.loadtxt` or `np.genfromtxt` or `pandas` and pass data to `Spectrum`. Similarly there is an `np.savetxt` for output.
