### ISSUE TITLE
Overview notebook

### ISSUE THREAD

**Issue by jccurtis** [lbl-anp/becquerel#94]

**Comment by markbandstra** [comment]
Here's a potential outline off the top of my head:

* Core
    * The `Spectrum` object
        - demonstrate how to instantiate the object with count data
        - I/O from standard file types
        - explain how uncertainties are handled
        - demonstrate various properties: e.g., `cps`, `cpskev`
        - demonstrate magic methods (add, sub, mul, div)
    * Calibrations
        - demonstrate how to instantiate a `LinearEnergyCal` and assign it to a `Spectrum`
        - calibrations are automatically created and included in a `Spectrum` when reading from a file
* Nuclear data tools
    * NNDC data
        - demonstrate how to fetch nuclear wallet card data for common isotopes, e.g., isotopes of potassium
        - demonstrate how to fetch gamma-ray lines for a common isotope, e.g., Cs-137
    * `Isotope`
        - demonstrate instantiation with, e.g., `'Carbon-12'`, `'K-40'`, and `'Tc-99m'`
        - demonstrate properties, e.g., `half_life`, `is_stable`, `decay_modes`, `j_pi`
        - demonstrate string formatting, e.g., `'{:%n(%s)-%a%m Z=%z A=%a}'.format(iso)`
* Material data tools
    * XCOM data
        - demonstrate how to fetch attenuation data for an element like Ge or Pb, and plot the results
        - same, but a compound like H2O
        - same, but a mixture like air
    * Material data
        - demonstrate element data with `materials.fetch_element_data()`
        - demonstrate compound data with `materials.fetch_compound_data()`
