### ISSUE TITLE
SPE file $PRESETS field

### ISSUE THREAD

**Issue by jccurtis** [lbl-anp/becquerel#98]
Reading the test spectrum (`1110C NAA cave pottery.Spe`) results in these warnings for the `$PRESETS` field:

```bash
Line 16414 unknown:  $PRESETS:
Line 16415 unknown:  Live Time
Line 16416 unknown:  86400
Line 16417 unknown:  0
```

We should added these as metadata of the `Spectrum` object as in  #81.

**Comment by chunhochow** [comment]
Do we know what options PRESETS could give?

In the example given, I assume livetime=86400, but what's the interpretation for the "0"..?

**Comment by jccurtis** [comment]
I'm not sure. It isn't listed on page 73 of this [manual](http://www.physics.rutgers.edu/ugrad/389/ORTEC%20File%20Structures.pdf). It is not present in this [random C spectrum converter](http://www.wheldon.talktalk.net/files/spec_conv.c) I just found. 

I think we can just add a warning that the PRESETS field is not currently parsed and leave it for now. Thoughts?

**Comment by cosama** [comment]
I found this: http://web.mit.edu/8.13/8.13d/manuals/Ortec-MAESTRO-software-manual.pdf. It mentions the presets on page 65. I assume that the 0 is the start channel.

Looking at the picture there of the presets dialog, I don't think any of these information are really important, as long as we get the true live time and run time (or dead time).

You can raise a warning if you like, I would just ignore it.

**Comment by chunhochow** [comment]
I agree with parsing what we can, and then just throw a warning on the rest. Same for #81 .
